name: Push

on:
  push:
    branches:
      - master
      - next

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release:
    needs: test

    uses: ./.github/workflows/release.yml
    secrets: inherit
